// svelte/personal-website/src/routes/components/Hero.svelte
<script>
    import CustomTypewriter from './CustomTypewriter.svelte';
    let strings = [
      { text: 'Full Stack Developer' },
      { text: 'Data Engineer' },
      { text: 'DevOps Enthusiast' }
    ];
  </script>
  
  <style>
    .hero {
      background-color: #2D2D2D;
      height: auto;
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      align-items: center;
      padding: 5rem 1rem;
      margin-bottom: 8rem;
    }
  
    .hero h1 {
      font-size: 1.875rem;
      font-weight: bold;
      margin-bottom: 1rem;
      color: #DD6B20;
    }
  
    .hero h2 {
      font-size: 1.125rem;
      color: white;
    }
  
    /* Adjust font sizes for larger screens */
    @media (min-width: 768px) {
      .hero h1 {
        font-size: 2.25rem;
      }
  
      .hero h2 {
        font-size: 1.25rem;
      }
    }
  
    @media (min-width: 1024px) {
      .hero h1 {
        font-size: 3rem;
      }
  
      .hero h2 {
        font-size: 1.5rem;
      }
    }
  
    @media (min-width: 1280px) {
      .hero h1 {
        font-size: 4rem;
      }
  
      .hero h2 {
        font-size: 1.875rem;
      }
    }
  </style>
  
  <div class="hero">
    <h1>Maximilian Huber</h1>
    <h2>
      <CustomTypewriter {strings} />
    </h2>
  </div>

// frontend/src/components/Hero.tsx
import React from 'react';
import CustomTypewriter from './customTypewriter';

const Hero: React.FC = () => {
  return (
    <div className="bg-darkGray h-auto flex flex-col justify-start items-center py-20 md:py-32 lg:py-40 mb-32">
      <h1 className="text-3xl md:text-4xl lg:text-6xl xl:text-8xl font-bold mb-4 text-dark-orange">
        Maximilian Huber
      </h1>
      <h2 className="text-lg md:text-xl lg:text-2xl xl:text-3xl text-white">
        <CustomTypewriter
          strings={[
            { text: 'Full Stack Developer' },
            { text: 'Data Engineer' },
            { text: 'DevOps Enthusiast' },
          ]}
          delay={75}
          loop
        />
      </h2>
    </div>
  );
};

export default Hero;
